### PR TITLE
Add additional flags such as workers, worker-connections and threads

### PR DESCRIPTION
**Pull request by derekbelrose**
Proposed For issue #97 
Purpose:
This PR proposes a change in the startup behavior of the image. It checks for the existence of certain environment variables and appends them to an ADDITIONAL_FLAGS string that is added to the gunicorn startup command. This change would allow additional flexibility in how the container can work in differing environments.

Changes:
Checks for environment variables WORKERS, CONNECTIONS and THREADS and adds them to the startup command for gunicorn

- Creates an entrypoint script so that we can inject some logic into the
startup
- Adds logic for adding flags based on environment variables and uses them in gunicorn startup

### CODE REVIEW

**Comment by cash** [comment]
thanks @derekbelrose. Can you also update the docker documentation (docs/DOCKER.rst)? 

@charman Thoughts on adding a bin directory? That's the only part I didn't like since it is only used by the docker images and might confuse people who are running it directly. Should we move the script into the docker-config directory?

**Comment by derekbelrose** [comment]
@cash I think moving it into the docker-config directory is a good idea and an easy fix. Are you fine with it living in the root of the image or would you prefer I move it into /opt/turkle, /usr/local/bin?

I'll update the docs as well

**Comment by derekbelrose** [comment]
Updated Docker docs as requested
Moved entrypoint.sh into scripts/ and pointed CMD to that instead.

**Comment by derekbelrose** [comment]
@cash I believe this is ready for your review again.  Thank you.

**Comment by cash** [comment]
Thanks. Will test this afternoon and then merge it in.

**Comment by cash** [comment]
I fixed two typos and then merged. Thanks for the work on this.

**Pull request merged**
