### PR TITLE
Added `completed` flag to Batch model

### LINKED ISSUE #85: Add `completed` flag to Batch model
The index page is too slow (#195).  Per the discussion in #203, one major contributing factor is the expense of the query checking if a Batch has any Tasks with available TaskAssignments for a User.

Adding a (properly updated) `completed` flag to the Batch model would improve the performance of queries checking if a Batch has any available Tasks.

The `Batch.completed` flag should be `True` IFF the `Task.completed` flag is `True` for all Tasks associated with a Batch.

The bookkeeping for maintaining the `Task.completed` and proposed `Batch.completed` flags will become more complicated if/when we add support for rejecting submitted TaskAssignments, as requested in #132.

Poster: Craig Harman   id: 274

### PR DESCRIPTION
**Pull request by charman**
Closes #85

### CODE REVIEW

**Comment by cash** [comment]
Was reviewing this and got confused by TaskAssignmen.save(). It sets the expire_at variable at the top of the method which makes me think that it is only called when the task assignment is created. Is this an incorrect understanding?

**Comment by cash** [comment]
Should an admin be able to mark a batch as completed manually? Let's say there are a few remaining assignments that no one did, but the requester is done with the project/batch.

**Comment by charman** [comment]
> Should an admin be able to mark a batch as completed manually? Let's say there are a few remaining assignments that no one did, but the requester is done with the project/batch.

I'd consider this to be an inactive but incomplete Batch. Admins can currently use the `Batch.active` to manually indicate that no further work should be done on a Batch. The `active` flag is only updated manually.

**Comment by charman** [comment]
> Was reviewing this and got confused by TaskAssignmen.save(). It sets the expire_at variable at the top of the method which makes me think that it is only called when the task assignment is created. Is this an incorrect understanding?

`TaskAssignment.save()` is called when a TaskAssignment is created and also when a TaskAssignment is updated:

https://docs.djangoproject.com/en/2.2/ref/models/instances/#how-django-knows-to-update-vs-insert

We may want to update `TaskAssignment.save()` to only update `expires_at` when the TaskAssignment is first created.

**Comment by cash** [comment]
If #51 gets implemented, it probably causes the task assignment to be deleted which wouldn't call the save() method causing the update_completed_status() from being called. Posting this as a reminder for the future.

**Comment by cash** [comment]
I don't have any other comments so looks good.

**Review by cash — APPROVED** [review]

**Pull request merged**
