### PR TITLE
Enable User-level access control 

### LINKED ISSUE #48: Enable User-level access control
Currently, Turkle restricts access at the Group level.

Based on discussions with @ateichert and @vandurme, there are use cases where access to Tasks should be restricted at the individual User level, instead of the Group level.

Poster: Craig Harman   id: 128

### PR DESCRIPTION
**Pull request by charman**
Closes #48

### CODE REVIEW

**Comment by charman** [comment]
The existing Turkle app already respects User-level access controls on Batches (which in practice, is implemented by associating the `can_work_on_batch` permission with a particular Batch-User pair).

This PR updates the admin UI to so that User-level access controls can now actually be assigned to both Projects and Batches. Matching the way that Group-level access controls are currently handled for Projects and Batches, the Project-level access controls are only used as the default settings for new Batches for a Project.

**Comment by cash** [comment]
Should the anonymous user be removed from the user selection box?

**Comment by cash** [comment]
Here is a bug that I'm seeing. I'm on this branch. The bug is not there on the master branch.

1. Edit an existing batch, restrict access, and set a group that your test user does not belong to
2. View the list of available batches with your test user (non-admin) and that user will see the batch that you've restricted

**Comment by charman** [comment]
> Should the anonymous user be removed from the user selection box?

Yes. Fixed in c90b313.

**Comment by charman** [comment]
> Here is a bug that I'm seeing. I'm on this branch. The bug is not there on the master branch.
> 
> 1. Edit an existing batch, restrict access, and set a group that your test user does not belong to
> 2. View the list of available batches with your test user (non-admin) and that user will see the batch that you've restricted

I'm having trouble reproducing this. When I follow these steps, the restricted batch is no longer shown to the (non-admin) user on the `index` page. Does the test suite (`python manage.py test`) pass when you run it locally? We have tests that are intended to verify this particular behavior.

**Comment by cash** [comment]
Just tried to reproduce and I wasn't able to. Checking to see if there are a longer series of steps.

**Comment by cash** [comment]
Should restricting a project to a group affect a batch that already existed or is it like other settings that only affects the batches creates after the setting was changed?

**Comment by charman** [comment]
> Should restricting a project to a group affect a batch that already existed or is it like other settings that only affects the batches creates after the setting was changed?

That may depend on which definition of "should" you are using.

**As implemented**, changes to Project permissions only affect new Batches, per [this comment](https://github.com/hltcoe/turkle/pull/141#issuecomment-821527917) earlier in the Issue thread:

> Matching the way that Group-level access controls are currently handled for Projects and Batches, the Project-level access controls are only used as the default settings for new Batches for a Project.

On the "Add/Change Project" page, the form widgets for selecting Groups and Users are under "Default Permissions for new Batches".

**Comment by cash** [comment]
I completely missed the heading as saying default for new batches. I haven't been able to reproduce the issue. I'm fine with merging this in.

**Pull request merged**
