### PR TITLE
Allow Projects to set default allotted assignment time for associated Batches

### PR DESCRIPTION
**Pull request by charman**

### CODE REVIEW

**Comment by cash** [comment]
As an FYI - I've worked a little on #54 and used the Django rest framework on a recent project. I should be able to carve out some time to finish it this month so we can get rewrite those client scripts.

**Comment by charman** [comment]
In an attempt to reduce confusion about how different Project settings are applied to Batches, I tried adding a new "Default Task Assignment Settings for new Batches" section heading to the "Add/Change Project" pages. The "Assignments per Task" and "Allotted Assignment Time" fields were moved into this new section. This new section is positioned above the existing "Default Permissions for new Batches" section.

Screen Shot 2021-04-07 at 3 09 43 PM

**Comment by cash** [comment]
I like the help text.

**Comment by charman** [comment]
Please note that the Project-level "default" settings for assignments_per_task and allotted_assignment_time are currently only used as defaults for new Batches that are created through the "Publish Tasks" button on the Project "changelist" page (e.g. http://127.0.0.1:8000/admin/turkle/project/).

Creating a `Batch` model instance through the Django APIs will initialize the `Batch.allotted_assignment_time` and `Batch.assignments_per_task` with the default values of these fields set in the Batch class.

Navigating directly to the "Add Batch" page and selecting a Project from the drop-down list will not cause form fields on the page to be dynamically updated with the default values from the selected Project.

**Comment by cash** [comment]
@charman How are other defaults handled when using "Add Batch"? Are any getting populated from the project or do the defaults only get set when navigating from "Publish Tasks"?

Should we consider removing the "Add Batch" option? I never use it and always go to the project and then click "Publish Tasks".

**Comment by charman** [comment]
When creating a new Batch, the "default" settings from the associated Project are only being "copied over" if we use the 'Publish Tasks' mechanism - but it looks like we are currently using two different mechanisms (GET parameters and server-side logic) to "copy over" the default Project values.

The 'Publish Tasks' button on the Project changelist page is a link to the 'Add Batch' page that pre-populates several GET parameters, including the `project` field. In the current master branch, the URL is generated by [turkle/admin.py#L996](https://github.com/hltcoe/turkle/blob/0ec24a2ee7405c30b36150068ccb2dcf4f4e0a01/turkle/admin.py#L996):

```python
        publish_tasks_url = '%s?project=%d&assignments_per_task=%d' % (
            reverse('turkle_admin:turkle_batch_add'),
            instance.id,
            instance.assignments_per_task)
```

Note that, in master, we are currently passing both the Project ID and the value of `Project.assignments_per_task` in as GET parameters. The current version of the PR also passes in the value of `Project.allotted_assignment_time` as a GET parameter.

The `BatchAdmin` model has logic that checks if the `project` field is set when adding a Batch -   [turkle/admin.py#L263](https://github.com/hltcoe/turkle/blob/0ec24a2ee7405c30b36150068ccb2dcf4f4e0a01/turkle/admin.py#L263):

```python
        if self.instance._state.adding and 'project' in self.initial:
            # We are adding a new Batch where the associated Project has been specified.
            # Per Django convention, the project ID is specified in the URL, e.g.:
            #   /admin/turkle/batch/add/?project=94

            # NOTE: The fields that are initialized here should match the fields copied
            #       over by the batch.copy_project_permissions() function.
```

When the 'Add Batch' page is displayed, the admin UI displays a form with default values that will be used to create a new `Batch` model instance, but the `Batch` model instance hasn't been created yet. If the `project` variable is set in the GET request when visiting the Add Batch page, then we currently have code that updates the form fields on the 'Add Batch' page using the 'default' permissions from the associated Project.

**Comment by charman** [comment]
With respect to:

> Should we consider removing the "Add Batch" option? I never use it and always go to the project and then click "Publish Tasks".

I'm not certain that we need the 'Add Batch' buttons, but overriding the default Django admin UI behaviors might be more trouble than it's worth.

**Comment by cash** [comment]
I checked the django documentation and there is a has_add_permission() method that can be added to the admin to remove the add button, but I expect that it prevents the create batch page from being hit also (did not test that).

**Comment by cash** [comment]
In the meeting yesterday, we discussed how it would be better to be consistent on how we handle defaults - copy them all over from project to batch server side before serving the form, then handle any GET url parameters as overrides. There was a question on whether we could do that with the permissions (groups).

We also discussed possibly moving the defaults code to client side JavaScript so that it could work for both the Publish Tasks and the Add Batch routes, but decided to stick with server side instead.

**Review by cash — APPROVED** [review]

**Comment by charman** [comment]
> I checked the django documentation and there is a has_add_permission() method that can be added to the admin to remove the add button, but I expect that it prevents the create batch page from being hit also (did not test that).

The Django admin UI uses the `has_add_permission()` method to determine whether or not to display the "Add Batch" buttons. You can see how this works in practice by creating a User with Staff (but not Superuser) status and grant the user CRUD access to Projects and R/U but not C/D access to Batches. The admin UI will show this user the "Change Batch" buttons, but the "Add Batch" buttons will be removed. Trying to use the "Publish Tasks" button generates an HTTP 403, Permission Denied error.

**Pull request merged**
