### PR TITLE
Add "calendar heatmap" visualization

### LINKED ISSUE #147: Add "calendar heatmap" visualization to Batch/Project Stats admin views
A "calendar heatmap" visualization makes it easy to see at a glance how much progress has been made per day on a Batch/Project, helping with project estimation/planning.

Examples of calendar heatmap visualizations:

https://github.com/wa0x6e/cal-heatmap
https://cal-heatmap.com

### PR DESCRIPTION
**Pull request by charman**
Closes #147

### CODE REVIEW

**Comment by charman** [comment]
The current draft PR uses cal-heatmap:

https://github.com/wa0x6e/cal-heatmap

cal-heatmap is well documented, but is no longer being actively developed. The most recent release was v3.6.2 on 2016-10-09.  cal-heatmap uses the 3.5.x series of the D3 library.  Version 4 of D3 (released on 2016-06-28) renamed some functions that cal-heatmap depends on.  The most recent release of D3 is currently 7.0.3.  Depending on an outdated version of D3 may preclude adding other D3-dependent visualizations to the relevant pages.

**Comment by charman** [comment]
Screenshot of Project Stats page with cal-heatmap visualization:

Screen Shot 2021-09-21 at 1 34 54 PM

**Comment by cash** [comment]
That looks really cool. How concerned are you with the lack of development on this package? I assuming it is fairly stable so the biggest issue as you mentioned is dependency conflict.

**Comment by cash** [comment]
sounds good.

**Comment by charman** [comment]
To partially address @paulmcnamee's long-standing request for #84, I was thinking of adding a "Show Activity in Last N Days" view that would display the "calendar heatmap" visualization for all Projects that have TaskAssignments completed within the last N days.

**Comment by cash** [comment]
Looks good. I am seeing an odd canceled request coming from d3 when the activity is loaded:
Screenshot from 2021-09-23 17-31-30

I cannot see any cause for it in the code.

**Comment by charman** [comment]
The canceled request for JSON data is apparently a known issue that was fixed in the master branch of cal-heatmap, but (based on the date of the comment from the package maintainer) was never included in an official release:

https://github.com/wa0x6e/cal-heatmap/issues/190

**Pull request merged**
